#!/usr/bin/env python3
"""Generates core/src/isdbt_tables_data.cpp from the text of ARIB STD-B31 (pypdf extraction of the English version 1.6-E2).
usage: gen_isdbt_tables.py b31.txt > core/src/isdbt_tables_data.cpp
Tables used: 3-13 (carrier randomizing), 3-14 / 3-15 (CP, AC and TMCC carriers), 3-16 (PRBS start values)."""
import re, sys

text = open(sys.argv[1], encoding='utf-8', errors='ignore').read().replace('\x0c', '')
lines = text.split('\n')

def find(pat, start=0):
    for i in range(start, len(lines)):
        if re.search(pat, lines[i]): return i
    raise SystemExit('not found: ' + pat)

# ---- Table 3-13: randomizing
rand = {}
for mode, tag in ((1, '(a)'), (2, '(b)'), (3, '(c)')):
    i = find(r'Table 3-13 \(%s\)' % tag[1])
    n = {1: 96, 2: 192, 3: 384}[mode]
    after = []
    j = i + 1
    while len(after) < n:
        l = lines[j].strip()
        if l.startswith('Before'):
            a = [int(x) for x in lines[j + 1].split()[1:]]
            # the 'Before' labels are taken by position: the printed table has a typo in one of them (mode 1, 74 for 72)
            after.extend(zip(range(len(after), len(after) + len(a)), a))
            j += 2
        else:
            j += 1
    table = [None] * n
    for b, a in after:
        table[b] = a
    assert None not in table and sorted(table) == list(range(n)), mode
    rand[mode] = table

# ---- Tables 3-14 / 3-15: carrier positions per segment, columns in the order 11 9 7 5 3 1 0 2 4 6 8 10 12
def rows(start_pat, end_pat, names):
    i = find(start_pat)
    k = find(end_pat, i + 1)
    out = {}
    for l in lines[i:k]:
        m = re.match(r'^\s*(CP|AC1_\s*\d+|AC2_\s*\d+|TMCC\s*\d+)\s+([\d ]+)$', l)
        if m:
            name = re.sub(r'\s+', '', m.group(1))
            vals = [int(x) for x in m.group(2).split()]
            if len(vals) == 13:
                out[name] = vals
    return out

diff = {
    1: rows(r'\(a\) Arrangement of the CP, AC, and TMCC Carriers in Mode 1', r'\(b\) Arrangement of the CP, AC, and TMCC Carriers in Mode 2', None),
    2: rows(r'\(b\) Arrangement of the CP, AC, and TMCC Carriers in Mode 2', r'\(c\) Arrangement of the CP, AC, and TMCC Carriers in Mode 3', None),
    3: rows(r'\(c\) Arrangement of the CP, AC, and TMCC Carriers in Mode 3', r'The CP of a differential modulation', None),
}
sync = {
    1: rows(r'\(a\) AC and TMCC Carrier Arrangements in Mode 1', r'\(b\) AC and TMCC Carrier Arrangements in Mode 2', None),
    2: rows(r'\(b\) AC and TMCC Carrier Arrangements in Mode 2', r'\(c\) AC and TMCC Carrier Arrangements in Mode 3', None),
    3: rows(r'\(c\) AC and TMCC Carrier Arrangements in Mode 3', r'The TMCC and AC \(AC1\) carriers are arranged', None),
}
expect_diff = {1: dict(ac1=2, ac2=4, tmcc=5), 2: dict(ac1=4, ac2=9, tmcc=10), 3: dict(ac1=8, ac2=19, tmcc=20)}
expect_sync = {1: dict(ac1=2, tmcc=1), 2: dict(ac1=4, tmcc=2), 3: dict(ac1=8, tmcc=4)}
for m in (1, 2, 3):
    for kind, cnt in (('AC1_', expect_diff[m]['ac1']), ('AC2_', expect_diff[m]['ac2']), ('TMCC', expect_diff[m]['tmcc'])):
        for n in range(1, cnt + 1):
            assert kind + str(n) in diff[m], (m, kind, n)
    for kind, cnt in (('AC1_', expect_sync[m]['ac1']), ('TMCC', expect_sync[m]['tmcc'])):
        for n in range(1, cnt + 1):
            assert kind + str(n) in sync[m], (m, kind, n)

# ---- Table 3-16: PRBS start values
i = find(r'Table 3-16: Initial Value')
init = {}
order = [11, 9, 7, 5, 3, 1, 0, 2, 4, 6, 8, 10, 12]
for l in lines[i:i + 40]:
    m = re.match(r'^\s*(\d+)\s+((?:[01]\s+){32}[01])\s*$', l)
    if m and int(m.group(1)) in order:
        bits = [int(x) for x in m.group(2).split()]
        init[int(m.group(1))] = (bits[0:11], bits[11:22], bits[22:33])
assert sorted(init) == list(range(13)), init.keys()

out = []
out.append('// Generated by tools/dev/gen_isdbt_tables.py from the tables of ARIB STD-B31 (3-13, 3-14, 3-15, 3-16). Do not edit.')
out.append('#include "dect2/isdbt.h"')
out.append('namespace dect2 {')
out.append('namespace isdbt {')
out.append('namespace tables {')
for m in (1, 2, 3):
    out.append('const uint16_t kRandomizing%d[%d] = {%s};' % (m, len(rand[m]), ','.join(map(str, rand[m]))))
# carriers[mode][segment index in frequency order 0..12] per kind
def emit(name, d, kinds):
    out.append('// %s: for each mode, for each kind, 13 carrier numbers in the order of segment numbers 11 9 7 5 3 1 0 2 4 6 8 10 12' % name)
for m in (1, 2, 3):
    ac1 = [diff[m]['AC1_%d' % n] for n in range(1, expect_diff[m]['ac1'] + 1)]
    ac2 = [diff[m]['AC2_%d' % n] for n in range(1, expect_diff[m]['ac2'] + 1)]
    tm = [diff[m]['TMCC%d' % n] for n in range(1, expect_diff[m]['tmcc'] + 1)]
    sac1 = [sync[m]['AC1_%d' % n] for n in range(1, expect_sync[m]['ac1'] + 1)]
    stm = [sync[m]['TMCC%d' % n] for n in range(1, expect_sync[m]['tmcc'] + 1)]
    for nm, arr in (('DiffAc1', ac1), ('DiffAc2', ac2), ('DiffTmcc', tm), ('SyncAc1', sac1), ('SyncTmcc', stm)):
        out.append('const uint16_t k%s%d[%d][13] = {%s};' % (nm, m, len(arr), ','.join('{' + ','.join(map(str, r)) + '}' for r in arr)))
for m in (1, 2, 3):
    out.append('const uint8_t kPrbsInit%d[13][11] = {%s};' % (m, ','.join('{' + ','.join(str(b) for b in init[s][m - 1]) + '}' for s in order)))
out.append('} // namespace tables')
out.append('} // namespace isdbt')
out.append('} // namespace dect2')
print('\n'.join(out))
